export const initialState = {
  loader: false,
  formData: {},
  tableData: [],
  totalItem: 10,
  refresh: false,
  columnOrder: [],
  columnValue: {},
  validationMessage: {},
  columnId: '',
  isColumnUpdated: false,
  sortColumn: '',
  sortDirection: '',
  isColumnModalOpen: false,
  pageNumber: 1,
  limit: 2,
  isEdit: false,
  userData: {},
};